//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class EmbeddedCortexClientWin : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EmbeddedCortexClientWin(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EmbeddedCortexClientWin obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EmbeddedCortexClientWin obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~EmbeddedCortexClientWin() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EmotivCortexLibPINVOKE.delete_CortexClient(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public EmbeddedCortexClientWin() : this(EmotivCortexLibPINVOKE.new_CortexClient(), true) {
  }

  public void sendRequest(string message) {
    EmotivCortexLibPINVOKE.CortexClient_sendRequest(swigCPtr, message);
    if (EmotivCortexLibPINVOKE.SWIGPendingException.Pending) throw EmotivCortexLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void registerResponseHandler(ResponseHandlerCpp handler) {
    EmotivCortexLibPINVOKE.CortexClient_registerResponseHandler(swigCPtr, ResponseHandlerCpp.getCPtr(handler));
  }

  public void close() {
    EmotivCortexLibPINVOKE.CortexClient_close(swigCPtr);
  }

}
