//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class EmotivCortexLibPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="SWIGRegisterExceptionCallbacks_EmotivCortexLib")]
    public static extern void SWIGRegisterExceptionCallbacks_EmotivCortexLib(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_EmotivCortexLib")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_EmotivCortexLib(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_EmotivCortexLib(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_EmotivCortexLib(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="SWIGRegisterStringCallback_EmotivCortexLib")]
    public static extern void SWIGRegisterStringCallback_EmotivCortexLib(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_EmotivCortexLib(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static EmotivCortexLibPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_delete_CortexStartedEventHandler")]
  public static extern void delete_CortexStartedEventHandler(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexStartedEventHandler_onCortexStarted")]
  public static extern void CortexStartedEventHandler_onCortexStarted(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_new_CortexStartedEventHandler")]
  public static extern global::System.IntPtr new_CortexStartedEventHandler();

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexStartedEventHandler_director_connect")]
  public static extern void CortexStartedEventHandler_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, CortexStartedEventHandler.SwigDelegateCortexStartedEventHandler_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_delete_CortexLogEventHandler")]
  public static extern void delete_CortexLogEventHandler(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexLogEventHandler_onLogMessage")]
  public static extern void CortexLogEventHandler_onLogMessage(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_new_CortexLogEventHandler")]
  public static extern global::System.IntPtr new_CortexLogEventHandler();

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexLogEventHandler_director_connect")]
  public static extern void CortexLogEventHandler_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, CortexLogEventHandler.SwigDelegateCortexLogEventHandler_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexLib_start")]
  public static extern void CortexLib_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexLib_stop")]
  public static extern void CortexLib_stop();

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexLib_setLogHandler")]
  public static extern void CortexLib_setLogHandler(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_new_CortexLib")]
  public static extern global::System.IntPtr new_CortexLib();

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_delete_CortexLib")]
  public static extern void delete_CortexLib(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_new_CortexClient")]
  public static extern global::System.IntPtr new_CortexClient();

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexClient_sendRequest")]
  public static extern void CortexClient_sendRequest(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexClient_registerResponseHandler")]
  public static extern void CortexClient_registerResponseHandler(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_CortexClient_close")]
  public static extern void CortexClient_close(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_delete_CortexClient")]
  public static extern void delete_CortexClient(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_ResponseHandlerCpp_processResponse")]
  public static extern void ResponseHandlerCpp_processResponse(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_delete_ResponseHandlerCpp")]
  public static extern void delete_ResponseHandlerCpp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_new_ResponseHandlerCpp")]
  public static extern global::System.IntPtr new_ResponseHandlerCpp();

  [global::System.Runtime.InteropServices.DllImport("EmotivCortexLib", EntryPoint="CSharp_ResponseHandlerCpp_director_connect")]
  public static extern void ResponseHandlerCpp_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, ResponseHandlerCpp.SwigDelegateResponseHandlerCpp_0 delegate0);
}
